// <auto-generated />
using System;
using GitCrawler.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitCrawler.Api.Data.Migrations
{
    [DbContext(typeof(GitCrawlerDbContext))]
    [Migration("20260801232544_AddCrawlerRawSignalFields")]
    partial class AddCrawlerRawSignalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommitCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ContributorCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ContributorCountFetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ForkCount")
                        .HasColumnType("integer");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastCrawledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LicenseName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PushedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StarCount")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CommitsPerWeek")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContributorCount")
                        .HasColumnType("integer");

                    b.Property<int>("ForkCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasLicense")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseType")
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.TrendAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("RepositoryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category", "PeriodStart");

                    b.ToTable("TrendAggregates");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Bookmark", b =>
                {
                    b.HasOne("GitCrawler.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Bookmarks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Score", b =>
                {
                    b.HasOne("GitCrawler.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Scores")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Summary", b =>
                {
                    b.HasOne("GitCrawler.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Summaries")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitCrawler.Api.Data.Entities.Repository", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Scores");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
